CREATE DATABASE Advocacia
GO

USE Advocacia
GO

/* Logico_1: */

CREATE TABLE ESCRITORIO (
    IDEscritorio INT IDENTITY(1, 1),
    Escritorio VARCHAR(100) NOT NULL,
    CONSTRAINT ESCRITORIO_IDEscritorio_PK PRIMARY KEY (IDEscritorio),
    CONSTRAINT ESCRITORIO_Escritorio_UN UNIQUE (Escritorio)
);
GO

CREATE TABLE PESSOA (
    IDPessoa INT IDENTITY(1, 1),
    Nome VARCHAR(100) NOT NULL,
    PFPJ CHAR(2) NOT NULL,
    CadastroTipo VARCHAR(8) NOT NULL,
    ID_Escritorio INT NOT NULL,
    CONSTRAINT PESSOA_IDPessoa_PK PRIMARY KEY (IDPessoa),
	CONSTRAINT PESSOA_PFPJ_CK CHECK(PFPJ IN ('PF', 'PJ')),
	CONSTRAINT PESSOA_CadastroTipo_CK CHECK(CadastroTipo IN ('Cliente', 'Adverso', 'Advogado')),
	CONSTRAINT PESSOA_ID_Escritorio_FK FOREIGN KEY (ID_Escritorio) REFERENCES ESCRITORIO(IDEscritorio)
);
GO

CREATE TABLE PROFISSAO (
    IDProfissao INT IDENTITY(1, 1),
    Profissao VARCHAR(100) NOT NULL,
    CONSTRAINT PROFISSAO_IDProfissao_PK PRIMARY KEY (IDProfissao),
	CONSTRAINT PROFISSAO_Profissao_UN UNIQUE (Profissao)    
);
GO

CREATE TABLE NACIONALIDADE (
    IDNacionalidade INT IDENTITY(1, 1),
    Nacionalidade VARCHAR(100) NOT NULL,
    CONSTRAINT NACIONALIDADE_IDNacionalidade_PK PRIMARY KEY (IDNacionalidade),
    CONSTRAINT NACIONALIDADE_Nacionalidade_UN UNIQUE (Nacionalidade)
);
GO

CREATE TABLE PF (
    IDPF_ID_Pessoa INT,
    CPF BIGINT NOT NULL,
    RG VARCHAR(10) NOT NULL,
    ExpedidorRG VARCHAR(100) NOT NULL,
    EstadoCivil VARCHAR(10) NOT NULL,
    Sexo CHAR(1) NOT NULL,
    DataDeNascimento DATE NOT NULL,
    ID_Profissao INT NOT NULL,
    ID_Nacionalidade INT NOT NULL,
    CONSTRAINT PF_IDPF_ID_Pessoa_PK PRIMARY KEY (IDPF_ID_Pessoa),
    CONSTRAINT PF_IDPF_ID_Pessoa_FK FOREIGN KEY (IDPF_ID_Pessoa) REFERENCES PESSOA(IDPessoa),
    CONSTRAINT PF_CPF_CK CHECK (CPF>0 AND CPF<=99999999999),
	CONSTRAINT PF_CPF_UN UNIQUE (CPF),
	CONSTRAINT PF_EstadoCivil_CK CHECK(EstadoCivil IN ('Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Separado(a)', 'Viuvo(a)')),
	CONSTRAINT PF_Sexo_CK CHECK(Sexo IN ('F', 'M')),
	CONSTRAINT PF_ID_Profissao_FK FOREIGN KEY (ID_Profissao) REFERENCES PROFISSAO(IDProfissao),
	CONSTRAINT PF_ID_Nacionalidade_FK FOREIGN KEY (ID_Nacionalidade) REFERENCES NACIONALIDADE(IDNacionalidade)
);
GO

CREATE TABLE PJ (
    IDPJ_ID_Pessoa INT,
    CNPJ BIGINT NOT NULL,
    Representante INT NOT NULL,
    CONSTRAINT PJ_IDPJ_ID_Pessoa_PK PRIMARY KEY (IDPJ_ID_Pessoa),
    CONSTRAINT PJ_IDPJ_ID_Pessoa_FK FOREIGN KEY (IDPJ_ID_Pessoa) REFERENCES PESSOA(IDPessoa),
    CONSTRAINT PJ_CNPJ_CK CHECK (CNPJ>0 AND CNPJ<=99999999999999),
	CONSTRAINT PJ_CNPJ_UN UNIQUE (CNPJ),
	CONSTRAINT PJ_Representante_FK FOREIGN KEY (Representante) REFERENCES PF(IDPF_ID_Pessoa)
);
GO

CREATE TABLE PRIVACIDADE (
    IDPrivacidade INT IDENTITY(1, 1),
    Privacidade VARCHAR(30) NOT NULL,
    CONSTRAINT PRIVACIDADE_IDPrivacidade_PK PRIMARY KEY (IDPrivacidade),
    CONSTRAINT PRIVACIDADE_Privacidade_UN UNIQUE (Privacidade)
);
GO

CREATE TABLE TELEFONE (
    IDTelefone INT IDENTITY(1, 1),
    TipoTelefone VARCHAR(30) NOT NULL,
    NumeroTelefone BIGINT NOT NULL,    
    ID_Privacidade INT NOT NULL,
    CONSTRAINT TELEFONE_IDTelefone_PK PRIMARY KEY (IDTelefone),
    CONSTRAINT TELEFONE_TipoTelefone_CK CHECK(TipoTelefone IN ('Celular', 'Fixo', 'Whatsapp')),
	CONSTRAINT TELEFONE_NumeroTelefone_CK CHECK (NumeroTelefone>99 AND NumeroTelefone<=99999999999),
	CONSTRAINT TELEFONE_NumeroTelefone_UN UNIQUE (NumeroTelefone),
	CONSTRAINT TELEFONE_ID_Privacidade_FK FOREIGN KEY (ID_Privacidade) REFERENCES PRIVACIDADE(IDPrivacidade)
);
GO

CREATE TABLE EMAIL (
    IDEmail INT IDENTITY(1, 1),
    Email VARCHAR(100) NOT NULL,
    ID_Privacidade INT NOT NULL,
    CONSTRAINT EMAIL_IDEmail_PK PRIMARY KEY (IDEmail),
    CONSTRAINT EMAIL_Email_CK CHECK (Email LIKE '%@%'),
    CONSTRAINT EMAIL_Email_UN UNIQUE (Email),
	CONSTRAINT EMAIL_ID_Privacidade_FK FOREIGN KEY (ID_Privacidade) REFERENCES PRIVACIDADE(IDPrivacidade)
);
GO

CREATE TABLE PESSOA_TELEFONE (
    ID_Pessoa INT NOT NULL,
    ID_Telefone INT NOT NULL,    
    CONSTRAINT PESSOA_TELEFONE_PK PRIMARY KEY (ID_Pessoa, ID_Telefone),
    CONSTRAINT PESSOA_TELEFONE_ID_Pessoa_FK FOREIGN KEY (ID_Pessoa) REFERENCES PESSOA(IDPessoa),
    CONSTRAINT PESSOA_TELEFONE_ID_Telefone_FK FOREIGN KEY (ID_Telefone) REFERENCES TELEFONE(IDTelefone)
);
GO

CREATE TABLE PESSOA_EMAIL (
    ID_Pessoa INT NOT NULL,
    ID_Email INT NOT NULL,
    CONSTRAINT PESSOA_EMAIL_PK PRIMARY KEY (ID_Pessoa, ID_Email),
    CONSTRAINT PESSOA_EMAIL_ID_Pessoa_FK FOREIGN KEY (ID_Pessoa) REFERENCES PESSOA(IDPessoa),
    CONSTRAINT PESSOA_EMAIL_ID_Email_FK FOREIGN KEY (ID_Email) REFERENCES EMAIL(IDEmail)    
);
GO

CREATE TABLE ESTADO (
    IDEstado INT IDENTITY(1, 1),
    Estado CHAR(2) NOT NULL,
    CONSTRAINT ESTADO_IDEstado_PK PRIMARY KEY (IDEstado),
    CONSTRAINT ESTADO_Estado_UN UNIQUE (Estado),
	CONSTRAINT ESTADO_Estado_CK CHECK(Estado IN ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA',
	'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'))
);
GO

CREATE TABLE CEP (
    IDCEP INT IDENTITY(1, 1),
    Logradouro VARCHAR(100) NOT NULL,
    Bairro VARCHAR(100) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    ID_Estado INT NOT NULL,
    CONSTRAINT CEP_IDCEP_PK PRIMARY KEY (IDCEP),
    CONSTRAINT CEP_IDCEP_UN UNIQUE (IDCEP),    
	CONSTRAINT CEP_ID_Estado_FK FOREIGN KEY (ID_Estado) REFERENCES ESTADO(IDEstado)
);
GO

CREATE TABLE ENDERECO (
    IDEndereco INT IDENTITY(1, 1),
    Numero VARCHAR(25) NOT NULL,
    ID_CEP INT NOT NULL,
    CONSTRAINT ENDERECO_IDEndereco_PK PRIMARY KEY (IDEndereco),
    CONSTRAINT ENDERECO_IDEndereco_UN UNIQUE (IDEndereco),    
	CONSTRAINT ENDERECO_ID_CEP_FK FOREIGN KEY (ID_CEP) REFERENCES CEP(IDCEP)
);
GO

CREATE TABLE COMPLEMENTO (
    IDComplemento_ID_Endereco INT NOT NULL,
    Complemento VARCHAR(25) NOT NULL,
    CONSTRAINT COMPLEMENTO_IDComplemento_ID_Endereco_PK PRIMARY KEY (IDComplemento_ID_Endereco),
    CONSTRAINT COMPLEMENTO_IDComplemento_ID_Endereco_UN UNIQUE (IDComplemento_ID_Endereco),
    CONSTRAINT COMPLEMENTO_IDComplemento_ID_Endereco_FK FOREIGN KEY (IDComplemento_ID_Endereco) REFERENCES ENDERECO(IDEndereco)
);
GO

CREATE TABLE PESSOA_ENDERECO (
    ID_Pessoa INT NOT NULL,
    ID_Endereco INT NOT NULL,
    CONSTRAINT PESSOA_ENDERECO_PK PRIMARY KEY (ID_Pessoa, ID_Endereco),
    CONSTRAINT PESSOA_ENDERECO_ID_Pessoa_FK FOREIGN KEY (ID_Pessoa) REFERENCES PESSOA(IDPessoa),
    CONSTRAINT PESSOA_ENDERECO_ID_Endereco_FK FOREIGN KEY (ID_Endereco) REFERENCES ENDERECO(IDEndereco)
);
GO

CREATE TABLE ADVOGADO (
    IDAdvogado_ID_Pessoa INT NOT NULL,
    OAB BIGINT NOT NULL,
    OABEstado INT NOT NULL,
    AdvogadoDefende INT NOT NULL,
    CONSTRAINT ADVOGADO_IDAdvogado_ID_Pessoa_PK PRIMARY KEY (IDAdvogado_ID_Pessoa),  
    CONSTRAINT ADVOGADO_IDAdvogado_ID_Pessoa_FK FOREIGN KEY (IDAdvogado_ID_Pessoa) REFERENCES PESSOA(IDPessoa),
    CONSTRAINT ADVOGADO_OAB_CK CHECK (OAB>0 AND OAB<=999999),
    CONSTRAINT ADVOGADO_OABEstado_FK FOREIGN KEY (OABEstado) REFERENCES ESTADO(IDEstado),
	CONSTRAINT ADVOGADO_AdvogadoDefende_FK FOREIGN KEY (AdvogadoDefende) REFERENCES PESSOA(IDPessoa)
);
GO

CREATE TABLE COMARCA (
    IDComarca INT IDENTITY(1, 1),
    Comarca VARCHAR(100) NOT NULL,    
    CONSTRAINT COMARCA_IDComarca_PK PRIMARY KEY (IDComarca),
    CONSTRAINT COMARCA_Comarca_UN UNIQUE (Comarca)    
);
GO

CREATE TABLE VARA (
    IDVara INT IDENTITY(1, 1),
    Vara VARCHAR(100) NOT NULL,
    CONSTRAINT VARA_IDVara_PK PRIMARY KEY (IDVara),
    CONSTRAINT VARA_Vara_UN UNIQUE (Vara)
);
GO

CREATE TABLE AREA (
    IDArea INT IDENTITY(1, 1),
    Area VARCHAR(100) NOT NULL,
    CONSTRAINT AREA_IDArea_PK PRIMARY KEY (IDArea),
    CONSTRAINT AREA_Area_UN UNIQUE (Area)
);
GO

CREATE TABLE PROCESSOS (
    IDProcessos INT IDENTITY(1, 1),
    NumeroDoProcesso INT NOT NULL,
    ID_Vara INT NOT NULL,
    ID_Comarca INT NOT NULL,
    ID_Estado INT NOT NULL,
    ID_Area INT NOT NULL,
    ID_ProcessoApenso INT NOT NULL,
    CONSTRAINT PROCESSOS_IDProcessos_PK PRIMARY KEY (IDProcessos),
    CONSTRAINT PROCESSOS_NumeroDoProcesso_UN UNIQUE (NumeroDoProcesso),    
    CONSTRAINT PROCESSOS_NumeroDoProcesso_CK CHECK (NumeroDoProcesso>0 AND NumeroDoProcesso<=99999999999999999999),
    CONSTRAINT PROCESSOS_ID_Vara_FK FOREIGN KEY (ID_Vara) REFERENCES VARA(IDVara),
	CONSTRAINT PROCESSOS_ID_Comarca_FK FOREIGN KEY (ID_Comarca) REFERENCES COMARCA(IDComarca),
    CONSTRAINT PROCESSOS_ID_Estado_FK FOREIGN KEY (ID_Estado) REFERENCES ESTADO(IDEstado),
    CONSTRAINT PROCESSOS_ID_Area_FK FOREIGN KEY (ID_Area) REFERENCES AREA(IDArea),
    CONSTRAINT PROCESSOS_ID_ProcessoApenso_FK FOREIGN KEY (ID_ProcessoApenso) REFERENCES PROCESSOS(IDProcessos),
);
GO

CREATE TABLE PARTE_PROCESSOS (
    ID_Pessoa INT NOT NULL,
    ID_Processos INT NOT NULL,
    Polo VARCHAR(8) NOT NULL,
    CONSTRAINT PARTE_PROCESSOS_PK PRIMARY KEY (ID_Pessoa, ID_Processos),    
    CONSTRAINT PARTE_PROCESSOS_Polo_CK CHECK (Polo IN ('Autor', 'Reu', 'Terceiro', 'Advogado')),	
	CONSTRAINT PARTE_PROCESSOS_ID_Pessoa_FK FOREIGN KEY (ID_Pessoa) REFERENCES PESSOA(IDPessoa),
    CONSTRAINT PARTE_PROCESSOS_ID_Processos_FK FOREIGN KEY (ID_Processos) REFERENCES PROCESSOS(IDProcessos)
);
GO

CREATE TABLE MODELO (
    IDModelo INT IDENTITY(1, 1),
    Atributos VARCHAR(100) NOT NULL,
    NomeModelo VARCHAR(100) NOT NULL,
    Tipo VARCHAR(100) NOT NULL,
    CONSTRAINT MODELO_IDModelo_PK PRIMARY KEY (IDModelo),
    CONSTRAINT MODELO_NomeModelo_UN UNIQUE (NomeModelo),
    CONSTRAINT MODELO_Tipo_CK CHECK (Tipo IN ('Peticoes', 'Documentos')),    
);
GO

CREATE TABLE PETICOES (
    IDPeticoes INT IDENTITY(1, 1),
    DataDoProtocolo DATE,
    Valores VARCHAR,
    ID_Processo INTEGER,
    ID_Modelo INTEGER
);
GO

CREATE TABLE DOCUMENTOS (
    IDDocumentos INTEGER PRIMARY KEY UNIQUE,
    Data DATE,
    Valores VARCHAR,
    ID_Modelo INTEGER,
    ID_Pessoa INTEGER
);
GO

CREATE TABLE PARTE_DOCUMENTOS (
    ID_Pessoa INTEGER,
    ID_Documentos INTEGER,
    ParteNoDocumento VARCHAR,
    PRIMARY KEY (ID_Pessoa, ID_Documentos)
);
GO




 